services:
  db:
    image: postgres:16
    container_name: pharmacy_postgres
    environment:
      POSTGRES_DB: pharmacy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pharmacy_pg_data:/var/lib/postgresql/data

volumes:
  pharmacy_pg_data:
