services:
  db:
    image: postgres:16
    container_name: hawi_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hawi_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpass@2026
    ports:
      - "5433:5432"
    volumes:
      - hawi_pgdata:/var/lib/postgresql/data

volumes:
  hawi_pgdata:
